services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'ftback'
      # So you don't have to use root, but you can if you like
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

    expose:
      - "3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    tty: true

  api:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env
